path_seg: '/content/drive/MyDrive/Datasets/LUNA16/seg-lungs-LUNA16/'
path_data: '/content/drive/MyDrive/Datasets/LUNA16/preprocessed_candidates/'
path_img_dest: '/content/drive/MyDrive/Datasets/LUNA16/inpainted_nodules/'
subset: 3
SKIP_IDX: [-1]
# SKIP_IDX: [0,1,2,3,4,5,6,7,8,9, 10,11,12,13,14,15,16,17,18,19, 20,21,22,23,24,25]

PLOT: True
OPT_OVER: 'net'
INPUT: 'noise'
INPUT_DEPTH: 192
EPOCHS: 5001 
param_noise: True
show_every: 500
reg_noise_std: 0.3

